public enum CodeEmitter {

    public static func emit(_ trie: BuiltTrie<UInt8>,
                            unicodeVersion: String,
                            globalName: String) -> String {
        var out = ""
        out += "// GENERATED by `swift run bedrock-ucd-gen`. Do not edit by hand.\n"
        out += "// Source: Sources/UnicodeProperties/UCD/UnicodeData.txt "
        out += "(Unicode \(unicodeVersion))\n"
        out += "\n"
        out += "@usableFromInline\n"
        out += "internal let \(globalName) = TwoStageTrie<UInt8>(\n"
        out += "    stage1: [\n"
        out += formatArray(trie.stage1.map { UInt($0) }, indent: "        ")
        out += "\n    ],\n"
        out += "    stage2: [\n"
        out += formatArray(trie.stage2.map { UInt($0) }, indent: "        ")
        out += "\n    ]\n"
        out += ")\n"
        return out
    }

    private static func formatArray(_ values: [UInt], indent: String) -> String {
        var out = indent
        for (i, v) in values.enumerated() {
            out += String(v)
            if i != values.count - 1 {
                out += ","
                if (i + 1) % 16 == 0 {
                    out += "\n" + indent
                } else {
                    out += " "
                }
            }
        }
        return out
    }
}
