public enum FlatArrayEmitter {

    public static func emit(_ array: [UInt32],
                            unicodeVersion: String,
                            globalName: String) -> String {
        var out = ""
        out += "// GENERATED by `swift run bedrock-ucd-gen`. Do not edit by hand.\n"
        out += "// Source: Sources/UnicodeProperties/UCD/CaseFolding.txt "
        out += "(Unicode \(unicodeVersion))\n"
        out += "\n"
        out += "@usableFromInline\n"
        out += "internal let \(globalName): [UInt32] = [\n"
        out += formatArray(array, indent: "    ")
        out += "\n]\n"
        return out
    }

    private static func formatArray(_ values: [UInt32], indent: String) -> String {
        if values.isEmpty { return indent }
        var out = indent
        for (i, v) in values.enumerated() {
            out += String(v)
            if i != values.count - 1 {
                out += ","
                if (i + 1) % 16 == 0 {
                    out += "\n" + indent
                } else {
                    out += " "
                }
            }
        }
        return out
    }
}
